{% set version = "0.1.3" %}

package:
 name: bed2gff
 version: {{ version }}

source:
 url: https://github.com/alejandrogzi/bed2gff/archive/refs/tags/v.{{ version }}.tar.gz
 sha256: c278185aba8c352ec2b14cc7db6eb08afb5b81e000b0acb9330bfccdad10506c 

build:
 number: 0
 script: cargo install --path . --root $PREFIX

requirements:
  build:
    - {{ compiler("cxx") }}
    - rust >=1.39
    - pkg-config
  host:
  run:

test:
 commands:
   - bed2gff --help
   - bed2gff --version

about:
 home: https://github.com/alejandrogzi/bed2gff
 license: MIT
 summary: "BED-to-GFF3 converter that runs in parallel"
extra:
  recipe-maintainers:
    - alejandrogzi
