{% set name = "gxt2bed" %}
{% set version = "0.1.0" %}

package:
  name: gxt2bed
  version: {{ version }}

source:
  url: https://github.com/alejandrogzi/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: XXX

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('gxt2bed', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler("cxx") }}
    - rust >=1.39
    - pkg-config

test:
  commands:
    - gxt2bed --help
    - gxt2bed --version

about:
  home: https://github.com/alejandrogzi/gxt2bed
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Fastest GTF/GFF-to-BED converter chilling around"

extra:
  recipe-maintainers:
    - alejandrogzi
