{% set version = "0.2.1" %}

package:
 name: gtfsort
 version: {{ version }}

source:
 url: https://github.com/alejandrogzi/gtfsort/archive/refs/tags/v.{{ version }}.tar.gz
 sha256: 0fdaa15e22bd34193e2b16b53697b413af0fcf485401f45d48ac48054f1d70f4 

build:
 number: 0
 script: cargo install --path . --root $PREFIX

requirements:
  build:
    - {{ compiler("cxx") }}
    - rust>=1.39
    - pkg-config
  host:
  run:

test:
 commands:
   - gtfsort --help
   - gtfsort --version

about:
 home: https://github.com/alejandrogzi/gtfsort
 license: MIT
 summary: "A chr/pos/feature GTF sorter that uses a lexicographically-based index ordering algorithm."

extra:
  recipe-maintainers:
    - alejandrogzi
