{% set version = "1.9.0" %}

package:
 name: bed2gtf
 version: {{ version }}

source:
 url: https://github.com/alejandrogzi/bed2gtf/archive/refs/tags/v.{{ version }}.tar.gz
 sha256: ae09861fa3474b3298a0469ad6d58bced91667792b5a20fdafe7b0dde6a05351

build:
 number: 0
 script: cargo install --path . --root $PREFIX

requirements:
  build:
    - {{ compiler("cxx") }}
    - rust >=1.39
    - pkg-config
  host:
  run:

test:
 commands:
   - bed2gtf --help
   - bed2gtf --version

about:
 home: https://github.com/alejandrogzi/bed2gtf
 license: MIT
 summary: "A high-performance BED-to-GTF converter written in Rust"
extra:
  recipe-maintainers:
    - alejandrogzi
